spring:
  application:
    name: sample-spring-elasticsearch
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200

  elasticsearch:
    rest:
      uris: http://localhost:9200

initial-import:
  enabled: false